const studentActions = {
  LOAD_ALL_STUDENTS: 'LOAD_ALL_STUDENTS',
  GET_ALL_STUDENTS: 'GET_ALL_STUDENTS',
  GET_LOAD_STUDENTS_ERROR: 'GET_LOAD_STUDENTS_ERROR',
  LOAD_STUDENT: 'LOAD_STUDENT',
  EDIT_STUDENT: 'EDIT_STUDENT',
  RESET_STUDENT: 'RESET_STUDENT',
  GET_LOAD_STUDENT_ERROR: 'GET_LOAD_STUDENT_ERROR',
  GET_STUDENT: 'GET_STUDENT',
  ADD_STUDENT: 'ADD_STUDENT',
  ADD_STUDENT_ERROR: 'ADD_STUDENT_ERROR',
  LOAD_STUDENT_ERROR: 'LOAD_STUDENT_ERROR',
  EDIT_STUDENT_ERROR: 'EDIT_STUDENT_ERROR',
  DELETE_STUDENT: 'DELETE_STUDENT',
  DELETE_STUDENT_ERROR: 'DELETE_STUDENT_ERROR',
};

export default studentActions;