const teacherActions = {
  LOAD_ALL_TEACHERS: 'LOAD_ALL_TEACHERS',
  GET_ALL_TEACHERS: 'GET_ALL_TEACHERSS',
  GET_LOAD_TEACHERS_ERROR: 'GET_LOAD_TEACHERS_ERROR',
  
  LOAD_SUBJECT: 'LOAD_SUBJECT',
  RESET_SUBJECT: 'RESET_SUBJECT',
  GET_SUBJECT: 'GET_SUBJECT',
  GET_LOAD_SUBJECTS_ERROR: 'GET_LOAD_SUBJECTS_ERROR',
  ADD_TEACHER: 'ADD_TEACHER',
  ADD_TEACHER_ERROR: 'ADD_TEACHER_ERROR',
  EDIT_SUBJECT: 'EDIT_SUBJECT',
  EDIT_SUBJECT_ERROR: 'EDIT_SUBJECT_ERROR',
  DELETE_SUBJECT: 'DELETE_SUBJECT',
  DELETE_SUBJECT_ERROR: 'DELETE_SUBJECT_ERROR',
};

export default teacherActions;