const teacherActions = {
  LOAD_ALL_TEACHERS: 'LOAD_ALL_TEACHERS',
  GET_ALL_TEACHERS: 'GET_ALL_TEACHERS',
  GET_LOAD_TEACHERS_ERROR: 'GET_LOAD_TEACHERS_ERROR',
  LOAD_TEACHER: 'LOAD_TEACHER',
  EDIT_TEACHER: 'EDIT_TEACHER',
  RESET_TEACHER: 'RESET_TEACHER',
  GET_LOAD_TEACHER_ERROR: 'GET_LOAD_TEACHER_ERROR',
  GET_TEACHER: 'GET_TEACHER',
  ADD_TEACHER: 'ADD_TEACHER',
  ADD_TEACHER_ERROR: 'ADD_TEACHER_ERROR',
  LOAD_TEACHER_ERROR: 'LOAD_TEACHER_ERROR',
  EDIT_TEACHER_ERROR: 'EDIT_TEACHER_ERROR',
  DELETE_TEACHER: 'DELETE_TEACHER',
  DELETE_TEACHER_ERROR: 'DELETE_TEACHER_ERROR',
};

export default teacherActions;