const batchActions = {
  LOAD_ALL_BATCHES: 'LOAD_ALL_BATCHES',
  GET_ALL_BATCHES: 'GET_ALL_BATCHES',
  LOAD_BATCH: 'LOAD_BATCH',
  RESET_BATCH: 'RESET_BATCH',
  LOAD_BATCH_ERROR: 'LOAD_BATCH_ERROR',
  GET_BATCH: 'GET_BATCH',
  GET_LOAD_BATCHES_ERROR: 'GET_LOAD_BATCHES_ERROR',
  ADD_BATCH: 'ADD_BATCH',
  ADD_BATCH_ERROR: 'ADD_BATCH_ERROR',
  EDIT_BATCH: 'EDIT_BATCH',
  EDIT_BATCH_ERROR: 'EDIT_BATCH_ERROR',
  DELETE_BATCH: 'DELETE_BATCH',
  DELETE_BATCH_ERROR: 'DELETE_BATCH_ERROR',
};

export default batchActions;