const academicActions = {
  LOAD_ALL_ACADEMICS: 'LOAD_ALL_ACADEMICS',
  GET_ALL_ACADEMICS: 'GET_ALL_ACADEMICS',
  LOAD_ACADEMIC: 'LOAD_ACADEMIC',
  RESET_ACADEMIC: 'RESET_ACADEMIC',
  LOAD_ACADEMIC_ERROR: 'LOAD_ACADEMIC_ERROR',
  GET_ACADEMIC: 'GET_ACADEMIC',
  GET_LOAD_ACADEMICS_ERROR: 'GET_LOAD_ACADEMICS_ERROR',
  ADD_ACADEMIC: 'ADD_ACADEMIC',
  ADD_ACADEMIC_ERROR: 'ADD_ACADEMIC_ERROR',
  EDIT_ACADEMIC: 'EDIT_ACADEMIC',
  EDIT_ACADEMIC_ERROR: 'EDIT_ACADEMIC_ERROR',
  DELETE_ACADEMIC: 'DELETE_ACADEMIC',
  DELETE_ACADEMIC_ERROR: 'DELETE_ACADEMIC_ERROR',
  LOAD_ACADEMIC_USERS: 'LOAD_ACADEMIC_USERS',
  GET_ACADEMIC_USERS: 'GET_ACADEMIC_USERS',
  LOAD_ALL_ACADEMICS_USERS: 'LOAD_ALL_ACADEMICS_USERS',
  DELETE_ACADEMIC_USERS_ERROR: 'DELETE_ACADEMIC_USERS_ERROR',
};

export default academicActions;