const loginActions = {
  LOGIN_DO: 'LOGIN_DO',
  GET_USER_DETAILS: 'GET_USER_DETAILS',
  DELETE_USER_DETAILS: 'DELETE_USER_DETAILS',
  GET_ALL_STUDENTS_REQUEST_ERROR: 'GET_ALL_STUDENTS_REQUEST_ERROR',
};

export default loginActions;