const classActions = {
  LOAD_ALL_CLASSES: 'LOAD_ALL_CLASSES',
  GET_ALL_CLASSES: 'GET_ALL_CLASSES',
  LOAD_CLASS: 'LOAD_CLASS',
  RESET_CLASS: 'RESET_CLASS',
  LOAD_CLASS_ERROR: 'LOAD_CLASS_ERROR',
  GET_CLASS: 'GET_CLASS',
  GET_LOAD_CLASSES_ERROR: 'GET_LOAD_CLASSES_ERROR',
  ADD_CLASS: 'ADD_CLASS',
  ADD_CLASS_ERROR: 'ADD_CLASS_ERROR',
  EDIT_CLASS: 'EDIT_CLASS',
  EDIT_CLASS_ERROR: 'EDIT_CLASS_ERROR',
  DELETE_CLASS: 'DELETE_CLASS',
  DELETE_CLASS_ERROR: 'DELETE_CLASS_ERROR',
};

export default classActions;