const subjectActions = {
  LOAD_ALL_SUBJECTS: 'LOAD_ALL_SUBJECTS',
  GET_ALL_SUBJECTS: 'GET_ALL_SUBJECTS',
  GET_LOAD_SUBJECTS_ERROR: 'GET_LOAD_SUBJECTS_ERROR',
  ADD_SUBJECT: 'ADD_SUBJECT',
  ADD_SUBJECT_ERROR: 'ADD_SUBJECT_ERROR',
};

export default subjectActions;