const subjectActions = {
  LOAD_ALL_SUBJECTS: 'LOAD_ALL_SUBJECTS',
  GET_ALL_SUBJECTS: 'GET_ALL_SUBJECTS',
  LOAD_SUBJECT: 'LOAD_SUBJECT',
  RESET_SUBJECT: 'RESET_SUBJECT',
  LOAD_SUBJECT_ERROR: 'LOAD_SUBJECT_ERROR',
  GET_SUBJECT: 'GET_SUBJECT',
  GET_LOAD_SUBJECTS_ERROR: 'GET_LOAD_SUBJECTS_ERROR',
  ADD_SUBJECT: 'ADD_SUBJECT',
  ADD_SUBJECT_ERROR: 'ADD_SUBJECT_ERROR',
  EDIT_SUBJECT: 'EDIT_SUBJECT',
  EDIT_SUBJECT_ERROR: 'EDIT_SUBJECT_ERROR',
  DELETE_SUBJECT: 'DELETE_SUBJECT',
  DELETE_SUBJECT_ERROR: 'DELETE_SUBJECT_ERROR',
};

export default subjectActions;